name: Publishing

on:
  push:
    tags:
      - '*'

jobs:

  publish-source:
    name: Publish source tarball
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      TWINE_REPOSITORY: testpypi
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python setup.py sdist
      - run: pip install twine
      - run: twine upload dist/*

  publish-linux-wheels-x64:
    name: Publish Linux wheels (x64)
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      TWINE_REPOSITORY: testpypi
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install cibuildwheel==1.6.3
      - run: cibuildwheel --output-dir wheelhouse
      - run: pip install twine
      - run: twine upload wheelhouse/*.whl
