name: Tests

on: [push, workflow_dispatch]

jobs:

  test-with-versions:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, pypy2, pypy3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install tox
      - run: tox
        env:
          TOXENV: ${{ matrix.python-version }}

  test-coverage:
    name: Run tests with coverage and report results to Coveralls.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          pip install tox
          pip install cython
          make cythonize
      - run: tox
        env:
          TOXENV: coveralls
          DEPENDENCY_INJECTOR_DEBUG_MODE: 1
          COVERALLS_REPO_TOKEN: ${{ COVERALLS_REPO_TOKEN }}
